---
include:
  - compose.infra.yml

services:
  server:
    profiles:
      - "full"
      - "backend"
    container_name: finsplitter
    build:
      context: .
      target: ${BUILD_TARGET:-dev-builder}
      dockerfile: Dockerfile
    command: dumb-init npm run start:dev -- --debug 0.0.0.0:${DEBUGGER_PORT}
    image: finsplitter:local
    ports:
      - "${PORT}:${PORT}"
      - "${DEBUGGER_PORT}:${DEBUGGER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - finsplitter